[context.deploy-preview]
  command = "npm run crowdin download && npm run build"
  publish = "build"

[build]
  command = "npm run crowdin:sync && npm run build"
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/static/admin"
  status = 200

[[plugins]]
package = "netlify-plugin-cache"
  [plugins.inputs]
  paths = [
    "node_modules/.cache/webpack",
  ]
